server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.17.167:3306/liujunpeng?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
mybatis-plus:
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itmuch.cloud.microserviceprovideruser.pojo
logging:
  level:
    com.itmuch.cloud.microserviceprovideruser.mapper: debug
  file:
    path: /log
    name: microserviceprovideruser.log
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.100.17.167:8761/eureka/,http://47.100.17.167:8762/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
ribbon:
  eureka:
    enabled: true #默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。
