server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.17.167:3306/liujunpeng?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    #password: 'redis'
    host: 47.100.17.167
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 30000
mybatis-plus:
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 2
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itmuch.cloud.microserviceprovideruser.pojo
logging:
  level:
    com.itmuch.cloud.microserviceprovideruser.mapper: debug
  file:
    path: /home/log
eureka:
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 3   # 心跳间隔
    lease-expiration-duration-in-seconds: 7 # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    ip-address: ${eureka.instance.hostname} # ip地址
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} # 注册列表显示的ip地址+服务名称+端口
  client:
    serviceUrl:
      #defaultZone: http://47.100.17.167:8761/eureka/    # 指定注册中心的地址
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
ribbon:
  eureka:
    enabled: true #默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，而是使用静态配置的服务列表。
