server:
  port: 8091
spring:
  application:
    name: SpringBootAdminServer
  boot:
    admin:
      ui:
        title: SpringBootAdmin-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
    hostname: 47.100.17.167
    ip-address: 47.100.17.167
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file:
    name: /home/springbootadmin/logs/microservice-springbootadmin-server.log