server:
  port: 8091
spring:
  application:
    name: Spring-BootAdmin
  boot:
    admin:
      ui:
        title: Spring-BootAdmin
eureka:
  client:
    serviceUrl:
      #defaultZone: http://47.100.17.167:8761/eureka/    # 指定注册中心的地址
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: 127.0.0.1
    ip-address: ${eureka.instance.hostname}
    lease-renewal-interval-in-seconds: 3   # 心跳间隔
    lease-expiration-duration-in-seconds: 7 # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file:
    name: /home/springbootadmin/logs/microservice-springbootadmin-server.log