spring:
  application:
    name: microservice-zuul
server:
  port: 8080
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 7
    lease-renewal-interval-in-seconds: 3
    ip-address: ${eureka.instance.hostname}
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
zuul:
  routes:
    microservice-provider-user: /user/**
logging:
  file:
    name: /home/zuul/logs/microservice-zuul.log