spring:
  profiles: eureka01
  application:
    name: SpringEureka-01
server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: 47.100.17.167         # 指定该Eureka实例的主机名
    preferIpAddress: true       # 使用IP注册
    lease-renewal-interval-in-seconds: 3   # 心跳间隔
    lease-expiration-duration-in-seconds: 7 # 服务失效时间： 如果多久没有收到请求，则可以删除服务
    ip-address: 47.100.17.167
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    # renewal-percent-threshold: 0.1
    enable-self-preservation: false   # 关闭自我保护模式
    # Eureka Server 自我保护系数，当enable-self-preservation=true时，启作用
    # renewal-percent-threshold:
    # 设置清理间隔,单位为毫秒,默认为0
    eviction-interval-timer-in-ms: 3000
    # 设置如果Eureka Server启动时无法从临近Eureka Server节点获取注册信息，它多久不对外提供注册服务
    wait-time-in-ms-when-sync-empty: 0
    # 集群之间相互更新节点信息的时间频率
    peer-eureka-nodes-update-interval-ms: 60000
logging:
  file:
    name: /home/eureka01/logs/microservice-eureka.log

